#pragma once

#include <stdint.h>

#define FLOWER_SPRITE_FRAME_COUNT 9
#define FLOWER_SPRITE_WIDTH 160
#define FLOWER_SPRITE_HEIGHT 86
#define FLOWER_SPRITE_PALETTE_SIZE 6

// Generated by tools/convert_flower_sprite.py. Do not hand-edit these arrays;
// edit assets/flower_animation.png and rerun the converter instead.
extern const uint16_t flower_sprite_palette[FLOWER_SPRITE_PALETTE_SIZE];
extern const uint8_t flower_sprite_frames[FLOWER_SPRITE_FRAME_COUNT][FLOWER_SPRITE_WIDTH * FLOWER_SPRITE_HEIGHT];
