#!/usr/bin/env python3
"""Convert the LumaBloom flower PNG into deterministic indexed C assets."""

from __future__ import annotations

import argparse
import struct
import zlib
from pathlib import Path


PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def read_rgba_png(path: Path) -> tuple[int, int, list[tuple[int, int, int, int]]]:
    data = path.read_bytes()
    if not data.startswith(PNG_SIGNATURE):
        raise ValueError("input is not a PNG")

    offset = len(PNG_SIGNATURE)
    width = height = color_type = bit_depth = None
    compressed = bytearray()

    while offset < len(data):
        length = struct.unpack(">I", data[offset : offset + 4])[0]
        chunk_type = data[offset + 4 : offset + 8]
        chunk_data = data[offset + 8 : offset + 8 + length]
        offset += 12 + length
        if chunk_type == b"IHDR":
            width, height, bit_depth, color_type, compression, filtering, interlace = struct.unpack(
                ">IIBBBBB", chunk_data
            )
            if (bit_depth, color_type, compression, filtering, interlace) != (8, 6, 0, 0, 0):
                raise ValueError("expected non-interlaced 8-bit RGBA PNG")
        elif chunk_type == b"IDAT":
            compressed.extend(chunk_data)
        elif chunk_type == b"IEND":
            break

    if width is None or height is None:
        raise ValueError("PNG has no IHDR")

    raw = zlib.decompress(bytes(compressed))
    stride = width * 4
    previous = bytearray(stride)
    pixels: list[tuple[int, int, int, int]] = []
    position = 0

    for _ in range(height):
        filter_type = raw[position]
        position += 1
        scanline = bytearray(raw[position : position + stride])
        position += stride
        for index in range(stride):
            left = scanline[index - 4] if index >= 4 else 0
            above = previous[index]
            upper_left = previous[index - 4] if index >= 4 else 0
            if filter_type == 1:
                scanline[index] = (scanline[index] + left) & 0xFF
            elif filter_type == 2:
                scanline[index] = (scanline[index] + above) & 0xFF
            elif filter_type == 3:
                scanline[index] = (scanline[index] + ((left + above) // 2)) & 0xFF
            elif filter_type == 4:
                estimate = left + above - upper_left
                pa = abs(estimate - left)
                pb = abs(estimate - above)
                pc = abs(estimate - upper_left)
                predictor = left if pa <= pb and pa <= pc else above if pb <= pc else upper_left
                scanline[index] = (scanline[index] + predictor) & 0xFF
            elif filter_type != 0:
                raise ValueError(f"unsupported PNG filter {filter_type}")
        pixels.extend(tuple(scanline[i : i + 4]) for i in range(0, stride, 4))
        previous = scanline

    return width, height, pixels


def panel_bgr565(color: tuple[int, int, int, int]) -> int:
    red, green, blue, alpha = color
    if alpha != 255:
        raise ValueError("sprite pixels must be fully opaque")
    # The ST7789 is configured with LCD_RGB_ELEMENT_ORDER_BGR, so place blue
    # in the high five bits and red in the low five bits of each pixel.
    return ((blue & 0xF8) << 8) | ((green & 0xFC) << 3) | (red >> 3)


def format_values(values: list[int], width: int = 24) -> str:
    lines = []
    for start in range(0, len(values), width):
        lines.append("    " + ", ".join(str(value) for value in values[start : start + width]) + ",")
    return "\n".join(lines)


def convert(source: Path, header: Path, implementation: Path) -> None:
    width, height, pixels = read_rgba_png(source)
    # Asset contract: the source is half the physical LCD resolution. Frames
    # are stacked top-to-bottom from closed/dark to open/bright.
    frame_width = 160
    frame_height = 86
    frame_count = 9
    if (width, height) != (frame_width, frame_height * frame_count):
        raise ValueError(f"expected 160x774 sprite sheet, got {width}x{height}")

    palette = sorted(set(pixels))
    if len(palette) > 256:
        raise ValueError(f"palette has {len(palette)} colors; maximum is 256")
    palette_index = {color: index for index, color in enumerate(palette)}
    indexed = [palette_index[color] for color in pixels]

    header.write_text(
        """#pragma once

#include <stdint.h>

#define FLOWER_SPRITE_FRAME_COUNT 9
#define FLOWER_SPRITE_WIDTH 160
#define FLOWER_SPRITE_HEIGHT 86
#define FLOWER_SPRITE_PALETTE_SIZE %d

// Generated by tools/convert_flower_sprite.py. Do not hand-edit these arrays;
// edit assets/flower_animation.png and rerun the converter instead.
extern const uint16_t flower_sprite_palette[FLOWER_SPRITE_PALETTE_SIZE];
extern const uint8_t flower_sprite_frames[FLOWER_SPRITE_FRAME_COUNT][FLOWER_SPRITE_WIDTH * FLOWER_SPRITE_HEIGHT];
"""
        % len(palette),
        encoding="utf-8",
        newline="\n",
    )

    frame_size = frame_width * frame_height
    frame_blocks = []
    for frame in range(frame_count):
        values = indexed[frame * frame_size : (frame + 1) * frame_size]
        frame_blocks.append("    {\n" + format_values(values) + "\n    },")

    implementation.write_text(
        '#include "flower_sprite_asset.h"\n\n'
        + "const uint16_t flower_sprite_palette[FLOWER_SPRITE_PALETTE_SIZE] = {\n    "
        + ", ".join(f"0x{panel_bgr565(color):04X}" for color in palette)
        + ",\n};\n\n"
        + "const uint8_t flower_sprite_frames[FLOWER_SPRITE_FRAME_COUNT][FLOWER_SPRITE_WIDTH * FLOWER_SPRITE_HEIGHT] = {\n"
        + "\n".join(frame_blocks)
        + "\n};\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"generated {frame_count} frames with {len(palette)} colors")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("header", type=Path)
    parser.add_argument("implementation", type=Path)
    args = parser.parse_args()
    convert(args.source, args.header, args.implementation)


if __name__ == "__main__":
    main()
